export const AUTH_SUCCESSFULL = 'AUTH_SUCCESSFULL';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_STARTED = 'AUTH_STARTED';
export const LOCAL_STORAGE_CHECKED = 'LOCAL_STORAGE_CHEACKED';
export const LOG_OUT = 'LOG_OUT';